import type { FormatPack } from "../../core/types.js";

export const webSeriesPack: FormatPack = {
  mediaType: "web_series",
  supported: true,
  status: "stable",
  directories: [
    "00_admin",
    "01_development",
    "02_episode_guides",
    "03_series_structure",
    "05_marketing",
    "07_website",
    "08_creators_and_talent",
    "14_platform_distribution",
    "15_sponsors_and_partnerships",
    "16_ops",
    "site",
    "site/assets",
  ],
  requiredFiles: [
    "README.md",
    "HANDOFF.md",
    "00_admin/canon_lock.yaml",
    "00_admin/package_manifest.json",
    "16_ops/missing_items_report.md",
    "16_ops/qa_checklists.md",
    "16_ops/approval_workflow.md",
    "01_development/web_series_deck.md",
    "01_development/series_overview.md",
    "02_episode_guides/episode_guide.md",
    "03_series_structure/arc_and_continuity.md",
    "05_marketing/audience_strategy.md",
    "05_marketing/social_content_plan.md",
    "08_creators_and_talent/creator_talent_kit.md",
    "14_platform_distribution/platform_release_plan.md",
    "15_sponsors_and_partnerships/sponsor_one_sheet.md",
    "07_website/website_content.md",
    "site/index.html",
    "site/about.html",
    "site/episodes.html",
    "site/talent.html",
    "site/sponsors.html",
    "site/faq.html",
    "site/assets/styles.css",
  ],
  templates: [
    {
      id: "web-readme-v1",
      mediaType: "web_series",
      department: "root",
      audience: ["internal", "partner", "press", "ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "README.md",
      templatePath: "src/templates/web-series/README.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.episodes", "canon.characters", "canon.storylines", "canon.tone", "canon.audience"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-handoff-v1",
      mediaType: "web_series",
      department: "root",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "HANDOFF.md",
      templatePath: "src/templates/web-series/HANDOFF.md.hbs",
      sources: ["canon.title", "canon.publication_flags", "canon.characters", "canon.episodes", "canon.storylines", "canon.locations"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-missing-v1",
      mediaType: "web_series",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/missing_items_report.md",
      templatePath: "src/templates/web-series/missing_items_report.md.hbs",
      sources: ["canon.business_assumptions", "canon.episodes"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "web-qa-v1",
      mediaType: "web_series",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/qa_checklists.md",
      templatePath: "src/templates/web-series/qa_checklists.md.hbs",
      sources: ["canon.title", "canon.episodes", "canon.characters"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "web-approval-v1",
      mediaType: "web_series",
      department: "ops",
      audience: ["ops", "producer", "legal"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/approval_workflow.md",
      templatePath: "src/templates/web-series/approval_workflow.md.hbs",
      sources: ["canon.title", "canon.publication_flags"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-deck-v1",
      mediaType: "web_series",
      department: "development",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/web_series_deck.md",
      templatePath: "src/templates/web-series/web_series_deck.md.hbs",
      sources: ["canon.logline", "canon.genre", "canon.audience", "canon.comps", "canon.tone", "canon.characters", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-overview-v1",
      mediaType: "web_series",
      department: "development",
      audience: ["internal", "partner", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/series_overview.md",
      templatePath: "src/templates/web-series/series_overview.md.hbs",
      sources: ["canon.logline", "canon.world_setting", "canon.locations", "canon.themes", "canon.tone", "canon.characters"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-episode-guide-v1",
      mediaType: "web_series",
      department: "episode_guides",
      audience: ["internal", "public"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "02_episode_guides/episode_guide.md",
      templatePath: "src/templates/web-series/episode_guide.md.hbs",
      sources: ["canon.episodes", "canon.duration_count", "canon.format"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-arc-v1",
      mediaType: "web_series",
      department: "series_structure",
      audience: ["internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "03_series_structure/arc_and_continuity.md",
      templatePath: "src/templates/web-series/arc_and_continuity.md.hbs",
      sources: ["canon.structure", "canon.themes", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-audience-v1",
      mediaType: "web_series",
      department: "marketing",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "05_marketing/audience_strategy.md",
      templatePath: "src/templates/web-series/audience_strategy.md.hbs",
      sources: ["canon.audience", "canon.comps", "canon.business_assumptions", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-social-plan-v1",
      mediaType: "web_series",
      department: "marketing",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "05_marketing/social_content_plan.md",
      templatePath: "src/templates/web-series/social_content_plan.md.hbs",
      sources: ["canon.title", "canon.themes", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-talent-v1",
      mediaType: "web_series",
      department: "creators_and_talent",
      audience: ["internal", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "08_creators_and_talent/creator_talent_kit.md",
      templatePath: "src/templates/web-series/creator_talent_kit.md.hbs",
      sources: ["canon.characters"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-platform-v1",
      mediaType: "web_series",
      department: "platform_distribution",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "14_platform_distribution/platform_release_plan.md",
      templatePath: "src/templates/web-series/platform_release_plan.md.hbs",
      sources: ["canon.business_assumptions", "canon.audience", "canon.duration_count", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-sponsor-v1",
      mediaType: "web_series",
      department: "sponsors_and_partnerships",
      audience: ["partner", "internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "15_sponsors_and_partnerships/sponsor_one_sheet.md",
      templatePath: "src/templates/web-series/sponsor_one_sheet.md.hbs",
      sources: ["canon.business_assumptions", "canon.audience", "canon.genre", "canon.tone", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "web-website-content-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "07_website/website_content.md",
      templatePath: "src/templates/web-series/website_content.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.episodes", "canon.characters", "canon.storylines", "canon.locations", "canon.tone", "canon.world_setting"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "web-site-index-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/index.html",
      templatePath: "src/templates/web-series/site/index.html.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "web-site-about-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/about.html",
      templatePath: "src/templates/web-series/site/about.html.hbs",
      sources: ["canon.world_setting", "canon.themes", "canon.tone"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "web-site-episodes-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/episodes.html",
      templatePath: "src/templates/web-series/site/episodes.html.hbs",
      sources: ["canon.episodes", "canon.duration_count"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "web-site-talent-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/talent.html",
      templatePath: "src/templates/web-series/site/talent.html.hbs",
      sources: ["canon.characters"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "web-site-sponsors-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public", "partner"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/sponsors.html",
      templatePath: "src/templates/web-series/site/sponsors.html.hbs",
      sources: ["canon.business_assumptions", "canon.audience"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "web-site-faq-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/faq.html",
      templatePath: "src/templates/web-series/site/faq.html.hbs",
      sources: ["canon.duration_count", "canon.format"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "web-site-styles-v1",
      mediaType: "web_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "css",
      path: "site/assets/styles.css",
      templatePath: "src/templates/web-series/site/assets/styles.css.hbs",
      sources: [],
      regenPolicy: "always",
      kind: "asset",
    },
  ],
};
