import type { FormatPack } from "../../core/types.js";

export const featureFilmPack: FormatPack = {
  mediaType: "feature_film",
  supported: true,
  status: "stable",
  directories: [
    "00_admin",
    "01_development",
    "02_scripts",
    "03_story_design",
    "06_press_kit",
    "07_website",
    "10_finance",
    "11_legal",
    "14_distribution",
    "16_ops",
    "site",
    "site/assets",
  ],
  requiredFiles: [
    "README.md",
    "HANDOFF.md",
    "00_admin/canon_lock.yaml",
    "00_admin/package_manifest.json",
    "16_ops/missing_items_report.md",
    "16_ops/qa_checklists.md",
    "16_ops/approval_workflow.md",
    "01_development/one_page_film_overview.md",
    "01_development/feature_treatment.md",
    "01_development/storyline_arc_document.md",
    "01_development/world_guide.md",
    "02_scripts/feature_screenplay.md",
    "03_story_design/visual_approach_lookbook.md",
    "10_finance/feature_budget_top_sheet.md",
    "10_finance/financing_memo.md",
    "11_legal/rights_and_chain_of_title.md",
    "14_distribution/festival_strategy.md",
    "06_press_kit/press_kit.md",
    "07_website/website_content.md",
    "site/index.html",
    "site/about.html",
    "site/story.html",
    "site/characters.html",
    "site/press.html",
    "site/partners.html",
    "site/assets/styles.css",
  ],
  templates: [
    {
      id: "film-readme-v1",
      mediaType: "feature_film",
      department: "root",
      audience: ["internal", "partner", "press", "ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "README.md",
      templatePath: "src/templates/film/README.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.characters", "canon.structure", "canon.storylines", "canon.tone", "canon.audience"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-handoff-v1",
      mediaType: "feature_film",
      department: "root",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "HANDOFF.md",
      templatePath: "src/templates/film/HANDOFF.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.format", "canon.publication_flags", "canon.structure", "canon.characters", "canon.storylines", "canon.locations"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-missing-v1",
      mediaType: "feature_film",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/missing_items_report.md",
      templatePath: "src/templates/film/missing_items_report.md.hbs",
      sources: ["canon.business_assumptions", "canon.legal_assumptions", "canon.structure"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "film-qa-v1",
      mediaType: "feature_film",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/qa_checklists.md",
      templatePath: "src/templates/film/qa_checklists.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.structure"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "film-approval-v1",
      mediaType: "feature_film",
      department: "ops",
      audience: ["ops", "legal", "producer"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/approval_workflow.md",
      templatePath: "src/templates/film/approval_workflow.md.hbs",
      sources: ["canon.title", "canon.publication_flags"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-overview-v1",
      mediaType: "feature_film",
      department: "development",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/one_page_film_overview.md",
      templatePath: "src/templates/film/one_page_film_overview.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.tone", "canon.comps", "canon.audience", "canon.world_setting", "canon.characters", "canon.structure", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-treatment-v1",
      mediaType: "feature_film",
      department: "development",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/feature_treatment.md",
      templatePath: "src/templates/film/feature_treatment.md.hbs",
      sources: ["canon.logline", "canon.world_setting", "canon.locations", "canon.themes", "canon.themes_structured", "canon.characters", "canon.structure", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-storyline-arc-v1",
      mediaType: "feature_film",
      department: "development",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/storyline_arc_document.md",
      templatePath: "src/templates/film/storyline_arc_document.md.hbs",
      sources: ["canon.title", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-world-guide-v1",
      mediaType: "feature_film",
      department: "development",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/world_guide.md",
      templatePath: "src/templates/film/world_guide.md.hbs",
      sources: ["canon.title", "canon.world_setting", "canon.locations", "canon.world_lore", "canon.factions"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-screenplay-v1",
      mediaType: "feature_film",
      department: "scripts",
      audience: ["internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "02_scripts/feature_screenplay.md",
      templatePath: "src/templates/film/feature_screenplay.md.hbs",
      sources: ["canon.title", "canon.structure", "canon.characters", "canon.storylines", "canon.episodes", "canon.genre", "canon.duration_count"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-lookbook-v1",
      mediaType: "feature_film",
      department: "story_design",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "03_story_design/visual_approach_lookbook.md",
      templatePath: "src/templates/film/visual_approach_lookbook.md.hbs",
      sources: ["canon.tone", "canon.world_setting", "canon.genre", "canon.locations", "canon.motifs"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-budget-v1",
      mediaType: "feature_film",
      department: "finance",
      audience: ["producer", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "10_finance/feature_budget_top_sheet.md",
      templatePath: "src/templates/film/feature_budget_top_sheet.md.hbs",
      sources: ["canon.production_assumptions", "canon.business_assumptions", "canon.locations", "canon.characters", "canon.structure"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-financing-v1",
      mediaType: "feature_film",
      department: "finance",
      audience: ["producer", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "10_finance/financing_memo.md",
      templatePath: "src/templates/film/financing_memo.md.hbs",
      sources: ["canon.business_assumptions", "canon.audience", "canon.comps", "canon.genre", "canon.tone", "canon.characters", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-rights-v1",
      mediaType: "feature_film",
      department: "legal",
      audience: ["legal", "producer"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "11_legal/rights_and_chain_of_title.md",
      templatePath: "src/templates/film/rights_and_chain_of_title.md.hbs",
      sources: ["canon.legal_assumptions", "canon.title", "canon.locations", "canon.factions"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-festival-v1",
      mediaType: "feature_film",
      department: "distribution",
      audience: ["partner", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "14_distribution/festival_strategy.md",
      templatePath: "src/templates/film/festival_strategy.md.hbs",
      sources: ["canon.audience", "canon.comps", "canon.genre", "canon.duration_count", "canon.tone", "canon.themes", "canon.storylines"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-press-kit-v1",
      mediaType: "feature_film",
      department: "press",
      audience: ["press", "partner", "public"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "06_press_kit/press_kit.md",
      templatePath: "src/templates/film/press_kit.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.comps", "canon.characters", "canon.storylines", "canon.tone", "canon.world_setting", "canon.duration_count"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "film-website-content-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["public", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "07_website/website_content.md",
      templatePath: "src/templates/film/website_content.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.structure", "canon.characters", "canon.storylines", "canon.themes", "canon.locations", "canon.tone", "canon.world_setting"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "film-site-index-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/index.html",
      templatePath: "src/templates/film/site/index.html.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.characters"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "film-site-about-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/about.html",
      templatePath: "src/templates/film/site/about.html.hbs",
      sources: ["canon.title", "canon.world_setting", "canon.themes", "canon.tone"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "film-site-story-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/story.html",
      templatePath: "src/templates/film/site/story.html.hbs",
      sources: ["canon.structure", "canon.title"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "film-site-characters-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/characters.html",
      templatePath: "src/templates/film/site/characters.html.hbs",
      sources: ["canon.characters", "canon.title"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "film-site-press-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["public", "press"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/press.html",
      templatePath: "src/templates/film/site/press.html.hbs",
      sources: ["canon.title", "canon.logline", "canon.comps"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "film-site-partners-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["partner"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/partners.html",
      templatePath: "src/templates/film/site/partners.html.hbs",
      sources: ["canon.business_assumptions", "canon.audience", "canon.comps"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "film-site-styles-v1",
      mediaType: "feature_film",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "css",
      path: "site/assets/styles.css",
      templatePath: "src/templates/film/site/assets/styles.css.hbs",
      sources: [],
      regenPolicy: "always",
      kind: "asset",
    },
  ],
};
