import type { FormatPack } from "../../core/types.js";

export const podcastPack: FormatPack = {
  mediaType: "podcast",
  supported: true,
  status: "stable",
  directories: [
    "00_admin",
    "01_development",
    "02_episode_design",
    "05_marketing",
    "06_press_kit",
    "07_website",
    "08_host_talent",
    "13_release_prep",
    "14_distribution",
    "15_business_dev",
    "16_ops",
    "site",
    "site/assets",
  ],
  requiredFiles: [
    "README.md",
    "HANDOFF.md",
    "00_admin/canon_lock.yaml",
    "00_admin/package_manifest.json",
    "16_ops/missing_items_report.md",
    "16_ops/qa_checklists.md",
    "16_ops/approval_workflow.md",
    "01_development/show_bible.md",
    "02_episode_design/episode_format.md",
    "02_episode_design/episode_guide.md",
    "08_host_talent/host_talent_kit.md",
    "14_distribution/platform_strategy.md",
    "15_business_dev/ad_inventory_model.md",
    "06_press_kit/launch_press_kit.md",
    "13_release_prep/trailer_script.md",
    "07_website/website_content.md",
    "site/index.html",
    "site/about.html",
    "site/episodes.html",
    "site/hosts.html",
    "site/advertise.html",
    "site/press.html",
    "site/faq.html",
    "site/assets/styles.css",
  ],
  templates: [
    {
      id: "podcast-readme-v1",
      mediaType: "podcast",
      department: "root",
      audience: ["internal", "partner", "press", "ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "README.md",
      templatePath: "src/templates/podcast/README.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.characters", "canon.episodes"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-handoff-v1",
      mediaType: "podcast",
      department: "root",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "HANDOFF.md",
      templatePath: "src/templates/podcast/HANDOFF.md.hbs",
      sources: ["canon.title", "canon.publication_flags", "canon.format"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-missing-v1",
      mediaType: "podcast",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/missing_items_report.md",
      templatePath: "src/templates/podcast/missing_items_report.md.hbs",
      sources: ["canon.business_assumptions", "canon.legal_assumptions"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "podcast-qa-v1",
      mediaType: "podcast",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/qa_checklists.md",
      templatePath: "src/templates/podcast/qa_checklists.md.hbs",
      sources: ["canon.title", "canon.episodes", "canon.characters"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "podcast-approval-v1",
      mediaType: "podcast",
      department: "ops",
      audience: ["ops", "legal", "producer"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/approval_workflow.md",
      templatePath: "src/templates/podcast/approval_workflow.md.hbs",
      sources: ["canon.title", "canon.publication_flags"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-show-bible-v1",
      mediaType: "podcast",
      department: "development",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/show_bible.md",
      templatePath: "src/templates/podcast/show_bible.md.hbs",
      sources: ["canon.logline", "canon.tone", "canon.themes", "canon.world_setting"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-episode-format-v1",
      mediaType: "podcast",
      department: "episode_design",
      audience: ["internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "02_episode_design/episode_format.md",
      templatePath: "src/templates/podcast/episode_format.md.hbs",
      sources: ["canon.duration_count", "canon.tone", "canon.production_assumptions"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-episode-guide-v1",
      mediaType: "podcast",
      department: "episode_design",
      audience: ["internal", "public"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "02_episode_design/episode_guide.md",
      templatePath: "src/templates/podcast/episode_guide.md.hbs",
      sources: ["canon.episodes"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-host-kit-v1",
      mediaType: "podcast",
      department: "host_talent",
      audience: ["internal", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "08_host_talent/host_talent_kit.md",
      templatePath: "src/templates/podcast/host_talent_kit.md.hbs",
      sources: ["canon.characters"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-platform-v1",
      mediaType: "podcast",
      department: "distribution",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "14_distribution/platform_strategy.md",
      templatePath: "src/templates/podcast/platform_strategy.md.hbs",
      sources: ["canon.audience", "canon.business_assumptions"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-ad-model-v1",
      mediaType: "podcast",
      department: "business_dev",
      audience: ["partner", "internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "15_business_dev/ad_inventory_model.md",
      templatePath: "src/templates/podcast/ad_inventory_model.md.hbs",
      sources: ["canon.business_assumptions", "canon.audience"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-press-kit-v1",
      mediaType: "podcast",
      department: "press",
      audience: ["press", "public", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "06_press_kit/launch_press_kit.md",
      templatePath: "src/templates/podcast/launch_press_kit.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.characters", "canon.comps"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-trailer-v1",
      mediaType: "podcast",
      department: "release_prep",
      audience: ["internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "13_release_prep/trailer_script.md",
      templatePath: "src/templates/podcast/trailer_script.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.characters"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "podcast-website-content-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "07_website/website_content.md",
      templatePath: "src/templates/podcast/website_content.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.characters", "canon.episodes"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "podcast-site-index-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/index.html",
      templatePath: "src/templates/podcast/site/index.html.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.characters"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "podcast-site-about-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/about.html",
      templatePath: "src/templates/podcast/site/about.html.hbs",
      sources: ["canon.world_setting", "canon.themes", "canon.tone"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "podcast-site-episodes-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/episodes.html",
      templatePath: "src/templates/podcast/site/episodes.html.hbs",
      sources: ["canon.episodes"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "podcast-site-hosts-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/hosts.html",
      templatePath: "src/templates/podcast/site/hosts.html.hbs",
      sources: ["canon.characters"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "podcast-site-advertise-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public", "partner"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/advertise.html",
      templatePath: "src/templates/podcast/site/advertise.html.hbs",
      sources: ["canon.business_assumptions", "canon.audience"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "podcast-site-press-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public", "press"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/press.html",
      templatePath: "src/templates/podcast/site/press.html.hbs",
      sources: ["canon.logline", "canon.comps"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "podcast-site-faq-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/faq.html",
      templatePath: "src/templates/podcast/site/faq.html.hbs",
      sources: ["canon.format", "canon.duration_count", "canon.publication_flags"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "podcast-site-styles-v1",
      mediaType: "podcast",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "css",
      path: "site/assets/styles.css",
      templatePath: "src/templates/podcast/site/assets/styles.css.hbs",
      sources: [],
      regenPolicy: "always",
      kind: "asset",
    },
  ],
};
