import type { FormatPack } from "../../core/types.js";

export const tvFormatPack: FormatPack = {
  mediaType: "tv_series",
  supported: true,
  status: "stable",
  directories: [
    "00_admin",
    "01_development",
    "03_story_room",
    "creative",
    "05_marketing",
    "06_press_kit",
    "07_website",
    "10_finance",
    "11_legal",
    "12_production",
    "16_ops",
    "site",
    "site/assets",
  ],
  requiredFiles: [
    "README.md",
    "HANDOFF.md",
    "00_admin/canon_lock.yaml",
    "00_admin/package_manifest.json",
    "16_ops/missing_items_report.md",
    "16_ops/qa_checklists.md",
    "16_ops/approval_workflow.md",
    "01_development/series_bible.md",
    "01_development/character_bible.md",
    "03_story_room/episode_guide.md",
    "creative/storyline_arc_document.md",
    "creative/world_guide.md",
    "06_press_kit/press_kit.md",
    "07_website/website_content.md",
    "site/index.html",
    "site/about.html",
    "site/episodes.html",
    "site/characters.html",
    "site/press.html",
  ],
  templates: [
    {
      id: "tv-readme-v1",
      mediaType: "tv_series",
      department: "root",
      audience: ["internal", "partner", "press", "ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "README.md",
      templatePath: "src/templates/tv/README.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.characters", "canon.episodes", "canon.storylines", "canon.structure"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-handoff-v1",
      mediaType: "tv_series",
      department: "root",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "HANDOFF.md",
      templatePath: "src/templates/tv/HANDOFF.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.format", "canon.publication_flags", "canon.storylines", "canon.locations", "canon.production_assumptions", "canon.business_assumptions"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-missing-v1",
      mediaType: "tv_series",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/missing_items_report.md",
      templatePath: "src/templates/tv/missing_items_report.md.hbs",
      sources: ["canon.characters", "canon.episodes", "canon.business_assumptions", "canon.legal_assumptions"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "tv-qa-v1",
      mediaType: "tv_series",
      department: "ops",
      audience: ["ops"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/qa_checklists.md",
      templatePath: "src/templates/tv/qa_checklists.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.episodes"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "tv-approval-v1",
      mediaType: "tv_series",
      department: "ops",
      audience: ["ops", "legal", "producer"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "md",
      path: "16_ops/approval_workflow.md",
      templatePath: "src/templates/tv/approval_workflow.md.hbs",
      sources: ["canon.title", "canon.publication_flags"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-series-bible-v1",
      mediaType: "tv_series",
      department: "development",
      audience: ["internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/series_bible.md",
      templatePath: "src/templates/tv/series_bible.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.themes", "canon.themes_structured", "canon.world_setting", "canon.tone", "canon.locations", "canon.world_lore", "canon.characters", "canon.episodes", "canon.storylines", "canon.factions"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-character-bible-v1",
      mediaType: "tv_series",
      department: "development",
      audience: ["internal", "casting"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "01_development/character_bible.md",
      templatePath: "src/templates/tv/character_bible.md.hbs",
      sources: ["canon.characters", "canon.factions", "canon.title"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-episode-guide-v1",
      mediaType: "tv_series",
      department: "story",
      audience: ["internal", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "03_story_room/episode_guide.md",
      templatePath: "src/templates/tv/episode_guide.md.hbs",
      sources: ["canon.episodes", "canon.storylines", "canon.title", "canon.format", "canon.duration_count"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-storyline-arc-v1",
      mediaType: "tv_series",
      department: "creative",
      audience: ["internal"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "creative/storyline_arc_document.md",
      templatePath: "src/templates/tv/storyline_arc_document.md.hbs",
      sources: ["canon.storylines", "canon.episodes", "canon.title"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-world-guide-v1",
      mediaType: "tv_series",
      department: "creative",
      audience: ["internal", "partner"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "creative/world_guide.md",
      templatePath: "src/templates/tv/world_guide.md.hbs",
      sources: ["canon.title", "canon.world_setting", "canon.locations", "canon.world_lore", "canon.factions"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-press-kit-v1",
      mediaType: "tv_series",
      department: "press",
      audience: ["press", "partner", "public"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "06_press_kit/press_kit.md",
      templatePath: "src/templates/tv/press_kit.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.comps", "canon.characters", "canon.episodes", "canon.tone", "canon.audience", "canon.world_setting"],
      regenPolicy: "allowed_if_not_locked",
      kind: "doc",
    },
    {
      id: "tv-website-content-v1",
      mediaType: "tv_series",
      department: "website",
      audience: ["public", "press"],
      packageTier: ["standard", "full"],
      outputFormat: "md",
      path: "07_website/website_content.md",
      templatePath: "src/templates/tv/website_content.md.hbs",
      sources: ["canon.title", "canon.logline", "canon.episodes", "canon.characters", "canon.themes", "canon.themes_structured", "canon.locations", "canon.world_setting", "publicCanon.characters", "publicCanon.episodes"],
      regenPolicy: "always",
      kind: "doc",
    },
    {
      id: "site-index-v1",
      mediaType: "tv_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/index.html",
      templatePath: "src/templates/tv/site/index.html.hbs",
      sources: ["canon.title", "canon.logline", "canon.genre", "canon.characters", "canon.episodes"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "site-about-v1",
      mediaType: "tv_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/about.html",
      templatePath: "src/templates/tv/site/about.html.hbs",
      sources: ["canon.title", "canon.world_setting", "canon.themes", "canon.tone"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "site-episodes-v1",
      mediaType: "tv_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/episodes.html",
      templatePath: "src/templates/tv/site/episodes.html.hbs",
      sources: ["canon.episodes", "canon.title"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "site-characters-v1",
      mediaType: "tv_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/characters.html",
      templatePath: "src/templates/tv/site/characters.html.hbs",
      sources: ["canon.characters", "canon.title"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "site-press-v1",
      mediaType: "tv_series",
      department: "website",
      audience: ["public", "press"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "html",
      path: "site/press.html",
      templatePath: "src/templates/tv/site/press.html.hbs",
      sources: ["canon.title", "canon.logline", "canon.comps", "canon.genre"],
      regenPolicy: "always",
      kind: "site",
    },
    {
      id: "site-styles-v1",
      mediaType: "tv_series",
      department: "website",
      audience: ["public"],
      packageTier: ["light", "standard", "full"],
      outputFormat: "css",
      path: "site/assets/styles.css",
      templatePath: "src/templates/tv/site/assets/styles.css.hbs",
      sources: [],
      regenPolicy: "always",
      kind: "asset",
    },
  ],
};
